###############################
#### INLA test error       ####
#### plug-in approximation ####
###############################
wkdir <- getwd()
.libPaths("~/R/x86_64-redhat-linux-gnu-library/3.3/")
runserver = TRUE
## Priors mean and variance for rho and sigma
mu_r <- 500/6371
v_r <- (1000/6371)^2
mu_s <- 20
v_s <- 40^2

#### 1 Show effect of mesh pattern on the covariance
source("glbm/Experiment1a/Rscript/INLA_1meshEffect.R")

############################
## Conclusion from Test 1 ##
############################
## The regular mesh put a pattern on the precision matrix for some reason (Finite element related -- check with Finn!)
## We choose to use regular meshes generated based on GPS locations in the following experiments.
## Why? Because it is easy for visualizing the effect of update from GPS data.
## Irregular mesh tend to generate busy covariance pattern due to the irregular angle size of the triangluation.
## This is difficult to differentiate the effects of observation error and prior error.
## Such effect is especially strong when the mesh grid is sparse with uneven angle sizes.


#### 2 Compare effect of mesh sizes (use the regular meshes)
## We also run a test using dense irregular mesh generated by GPS locations for comparison
source("glbm/Experiment1a/Rscript/INLA_2testMesh.R")

############################
## Conclusion from Test 2 ##
############################


#### 3 Compare effect of pointwise error size
exname <- "/experimentBHM/PointErr_"
## Find a single and isolated point to test on with large and small error
## choose by eye -- no. 459
source("glbm/Experiment1a/Rscript/INLA_3testErr.R")
