###############################
#### INLA test error       ####
#### plug-in approximation ####
###############################
wkdir <- getwd()
runserver = TRUE
## Priors mean and variance for rho and sigma
mu_r <- 500/6371
v_r <- (1000/6371)^2
mu_s <- 20
v_s <- 40^2

#### 1 Show effect of mesh pattern on the covariance 
source("glbm/Experiment1a/Rscript/INLA_1meshEffect.R")

############################
## Conclusion from Test 1 ##
############################
## The regular mesh put a pattern on the precision matrix for some reason (Finite element related -- check with Finn!)
## We choose to use regular meshes generated based on GPS locations in the following experiments.
## Why? Because it is easy for visualizing the effect of update from GPS data.
## Irregular mesh tend to generate busy covariance pattern due to the irregular angle size of the triangluation.
## This is difficult to differentiate the effects of observation error and prior error.
## Such effect is especially strong when the mesh grid is sparse with uneven angle sizes.


#### 2 Compare effect of mesh sizes (use the regular meshes)
## We also run a test using dense irregular mesh generated by GPS locations for comparison 
source("glbm/Experiment1a/Rscript/INLA_2testMesh.R")



runserver = TRUE
exname <- "/experimentBHM/PointErr_"
load("experimentBHM/Mesh_GIAs.RData")
## Find a single and isolated point to test on with large and small error 
## cho0se by eye -- no. 417 and to illustrate the effect choose it to have the same sign 
## as the nearest points --no.128
err1 <- err2 <- err
err1[417] <- sign(err[128])*0.001
err2[417] <- sign(err[128])*50
source("glbm/Experiment1a/Rscript/4GP_inla_testErr.R")


### 2 Test general error size
runserver = TRUE
meshSize <- c("s", "m", "l")
errSize <- c("s", "L")
errors <- c(0.01, 2)

for(j in 1:2){
  err <- rnorm(nrow(GPS_obsU), sd = errors[j])
 
}


### 3 Test effect of mesh size
