##################################################################################
##         Test3     Polygon observations S2 != S1                              ##
##################################################################################
##       Test script for simulate and estimate a univariate process             ##
##   We use the coarse mesh generated on the globe and simulate a univariate GP ##
## with zero mean and matern kernal as the true process. Then the observed data ##
## is assumed to be true process plus Gaussian error.                           ##
##   We then infer the true process from the observatiosn by using the MVST     ##
## framework and plot the posterior means and error bars.                       ##
##                                                                              ##
## ***Mesh***                                                                   ##
## * We use the mesh saved in the object MeshGlobe.RData                        ##
##   which was generated by the script Mesh/globe_INLA.R                        ##
##                                                                              ##
## ***Steps***                                                                  ##
## * 0. Initialising and load the previously generated Mesh grid                ##
## * For situation k, we do                                                     ##
## * a. Simulate the true process and observations                              ##
## * b. Infer the process from observations                                     ##
## * c. Plot the results and save                                               ##
##################################################################################

#### 0. Set working directory, load data and packages 
setwd("O:/glbm/TestMVST/R")
load("C:/Users/zs16444/Local Documents/GlobalMass/TestIO/sim_1.RData")
library(INLA)
library(rgdal)
library(maptools)
library(GEOmap)
library(rgl)

library(dplyr)
library(ggplot2)
library(MVST)

### Set seed for reproducible results
set.seed(33)

################################################################################
## Asssume the true process follows a GP with zero mean and Matern kernel.    ##
## The true process is simulated at the triangulation vertices.               ## 
##                                                                            ##
## Denote by S1 the set of triangle vertices and                              ##
## S2 a set of spatial units where the observations are taken.                ##
## We simulate observations for the following 3 situations                    ##
################################################################################
################################################################################
### 3.a Simulate the true process and observed data 

## Generate S2 
## sample a few points from the mesh location and add some noises
mglb_tv <- MeshB$loc
ll_loc <- do.call(cbind, Lxyz2ll(list(x = mglb_tv[,1], y = mglb_tv[,2], z = mglb_tv[,3])))
newloc <- ll_loc[sample(1:nrow(ll_loc), 1000), ] + matrix(rnorm(2000, 10, 20), ncol = 2, nrow = 1000)
newloc <- newloc[(abs(newloc[,1]) <= 90) &  (abs(newloc[,2]) <= 180) , ] #remove impossible coords
obsloc <- do.call(cbind, Lll2xyz(lat = newloc[,1], lon = newloc[,2]))

## Use the previous S2 to generate a triangulation an muse use triangles 
## as the polygons
MeshS2 <- inla.mesh.2d(loc = obsloc, cutoff = 0.01, max.edge = 0.2)
summary(MeshS2)
plot(MeshS2, rgl = TRUE)

## Construct the Obs_poly object, using the generated mesh grid
## grid value take the average of the three vertex
n.poly <- nrow(MeshS2$graph$tv)
id <- 1:n.poly
tvid <- MeshS2$graph$tv # get the table of triangle vertex id
vloc <- MeshS2$loc # get the xyz coordinates of the vertex
poly_xys <- data.frame(do.call(rbind,lapply(id, function(x) c(t(apply(vloc[tvid[x,],], 1, xyz2ll))))))
names(poly_xys) <- c("x1", "x2", "x3", "y1", "y2", "y3")
poly_df <- cbind(id = id, poly_xys, t = 0)

## Find the centroid of each triangle and calculate the mean 
df_xy <- data.frame(do.call(rbind,lapply(id, function(x) rowMeans(apply(vloc[tvid[x,],], 1, xyz2ll)))))
names(df_xy) <- c("x", "y")
df_xy_loc <- do.call(cbind, Lll2xyz(lat = df_xy[,1],lon = df_xy[,2]))

loc_all <- rbind(mglb_tv, df_xy_loc)
mglb_S2b <- MVST::Matern(as.matrix(dist(loc_all)), nu = 3/2, var = 4, kappa = 0.1) # create the Matern covmat
mglb_Q2b <- GMRF(Q = as(chol2inv(chol(mglb_S2b)),"dgCMatrix")) # the precmat
mglb_x2ball <- sample_GMRF(mglb_Q2b) # simulate the true processs

n_S1 <- length(mglb_p@G@mu)
n_S2b <- nrow(df_xy_loc)
mglb_x2b <- mglb_x2ball[1:n_S1]
mglb_x2bobs <- mglb_x2ball[-(1:n_S1)]


df_val <- data.frame(z = sapply(id, function(x) mean(mglb_x2bobs[tvid[x,]]))) + rnorm(length(mglb_x2bobs))*sd2
dfS2b <- cbind(id = id, df_xy, df_val, std = sd2, t = 0)
Obs2b <- Obs_poly(df = dfS2b, pol_df = poly_df)
Obs2b_area <- sapply(Obs2b@pol, gpclib::area.poly)
Obs2b@df$z <- Obs2b@df$z * Obs2b_area
#save.image(file = "C:/Users/zs16444/Local Documents/Zhe/TestGIA.RData")
#load(file = "C:/Users/zs16444/Local Documents/Zhe/TestGIA.RData")



### 3.b Update the true process given the observations
## Use the GMRF basis and find the Cmat by FindC_polyareage
## Create the finite element object from the inla mesh
MeshB_fem <- inla.mesh.fem(MeshB, order = 2)
MeshBf <- initFEbasis(p=MeshB$loc,
                      t=MeshB$graph$tv,
                      M=MeshB_fem$c1,
                      K=MeshB_fem$g1)
mglb_p <- GMRF_basis(mglb_Q1, Basis = MeshBf)
## Build the LinkGo obj
L3 <- link(mglb_p, Obs2b, n_grid = 400)  # build from process
e3 <- new("link_list",list(L3))
v3 <- new("block_list",list(G1 = mglb_Q1, O = Obs2b))
G3 <- new("Graph",e = e3,v = v3)
G_reduced <- compress(G3)
Results3 <- Infer(G_reduced)

mglb_x2b_post <- Results3$Post_GMRF@rep
x2b_mpost<- mglb_x2b_post$x_mean
## Get the posterior mean and variance
x2b_spost <- sqrt(mglb_x2b_post$x_margvar)

## Compare mean square error with the true value
err2b <- x2b_mpost - mglb_x2b
mean(err2b^2)

par(mfrow=c(2,3))
plot(mglb_x2b)
plot(mglb_x2bobs)
plot(x2b_mpost, mglb_x2b)
plot(err2)
plot(x2b_spost)


### 3.c Plot and save results
## 3.c.1 Compare the true process and the observed values
## Palette setting 
clims <- range(c(mglb_x2ball, df_val, x2b_mpost))
clens <- round((clims[2] - clims[1])*100) + 1
colpal <- terrain.colors(clens, alpha=0)
colx2bobs <- colpal[round((mglb_x2bobs - clims[1])*100) + 1]
colx2true <- colpal[round((mglb_x2b - clims[1])*100) + 1]
coly2b <- colpal[round((df_val$z - clims[1])*100) + 1]
colxp2b <- colpal[round((x2b_mpost - clims[1])*100) + 1]
## Start plotting
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## Plot the true process
par3d(zoom = 0.8)
plot3d(vloc,  col = colx2bobs, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens, nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("The true process")
axis(1)})
## plot the observed value
next3d(reuse = FALSE)
par3d(zoom=0.8)
plot3d(obsloc,  col = coly2, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens), axes = FALSE,xlab = "",ylab = "")
title("Observed values")
axis(1)})
## Finish plotting and save the plot as an html
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/PvsObs2.html", width = 1500, reuse = TRUE)

## 3.c.2 Compare the Posterior Mean and variances
## reset palette
climss <- round(range(x2b_spost*20000))
clenss <- climss[2] - climss[1] + 1
colpals <- heat.colors(clenss, alpha=0)
colsp2 <- colpals[round(x2b_spost*20000) - climss[1]+1]
## Start plotting
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## The posterior mean
par3d(zoom = 0.8)
plot3d(obsloc,  col = colxp2, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation

next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("Posterior mean")
axis(1)})


next3d(reuse = FALSE)
par3d(zoom=0.8)
## The posterior marginal std
plot3d(obsloc, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colsp2, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation

next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clenss,nrow=clenss)
y=1
x=seq(min(x2_spost),max(x2_spost),len=clenss)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=heat.colors(clenss),axes=FALSE,xlab="",ylab="")
title("Posterior standard error")
axis(1)})
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/posterior2.html", width = 1500, reuse = TRUE)

save.image(file = "C:/Users/zs16444/Local Documents/GlobalMass/TestIO/Sim3all.RData")