##################################################################################
##         Test2    Point observations but S2 != S1                             ##
##################################################################################
##       Test script for simulate and estimate a univariate process             ##
##   We use the coarse mesh generated on the globe and simulate a univariate GP ##
## with zero mean and matern kernal as the true process. Then the observed data ##
## is assumed to be true process plus Gaussian error.                           ##
##   We then infer the true process from the observatiosn by using the MVST     ##
## framework and plot the posterior means and error bars.                       ##
##                                                                              ##
## ***Mesh***                                                                   ##
## * We use the mesh saved in the object MeshGlobe.RData                        ##
##   which was generated by the script Mesh/globe_INLA.R                        ##
##                                                                              ##
## ***Steps***                                                                  ##
## * 0. Initialising and load the previously generated Mesh grid                ##
## * For situation k, we do                                                     ##
## * a. Simulate the true process and observations                              ##
## * b. Infer the process from observations                                     ##
## * c. Plot the results and save                                               ##
##################################################################################

#### 0. Set working directory, load data and packages 
setwd("O:/glbm/TestMVST/R")
load("../Results/Mesh/MeshB.RData")
library(INLA)
library(rgdal)
library(maptools)
library(GEOmap)
library(rgl)

library(dplyr)
library(ggplot2)
library(MVST)

### Set seed for reproducible results
set.seed(123)

################################################################################
## Asssume the true process follows a GP with zero mean and Matern kernel.    ##
## The true process is simulated at the triangulation vertices.               ## 
##                                                                            ##
## Denote by S1 the set of triangle vertices and                              ##
## S2 a set of spatial units where the observations are taken.                ##
################################################################################
################################################################################
### 2.a Simulate the true process and observed data 
## Generate S2 
## sample a few points from the mesh location and add some noises
ll_loc <- do.call(cbind, Lxyz2ll(list(x = mglb_tv[,1], y = mglb_tv[,2], z = mglb_tv[,3])))
newloc <- ll_loc[sample(1:nrow(ll_loc), 1000), ] + matrix(rnorm(2000, 10, 20), ncol = 2, nrow = 1000)
newloc <- newloc[(abs(newloc[,1]) <= 90) &  (abs(newloc[,2]) <= 180) , ] #remove impossible coords
obsloc <- do.call(cbind, Lll2xyz(lat = newloc[,1], lon = newloc[,2]))
plot3d(obsloc)

## Simulate the true process on S2 + S1
loc_all <- rbind(mglb_tv, obsloc)
mglb_S2all <- Matern(as.matrix(dist(loc_all)), nu = 3/2, var = 4, kappa = 0.1) # create the Matern covmat
mglb_Q2all <- GMRF(Q = as(chol2inv(chol(mglb_S2all)),"dgCMatrix")) # the precmat
mglb_x2all <- sample_GMRF(mglb_Q2all) # simulate the true processs
n_S1 <- nrow(mglb_tv)
n_S2 <- nrow(obsloc)
mglb_x2 <- mglb_x2all[1:n_S1]
mglb_x2obs <- mglb_x2all[-(1:n_S1)]


## Simulate the observations, assume the error is Gaussian with sd = 0.1
sd2 <- 0.1
mglb_y2 <- mglb_x2obs + rnorm(n_S2)*sd2
obs2 <- Obs(df=data.frame(x = obsloc[,1], y = obsloc[,2], w = obsloc[,3], z = mglb_y2, std = sd2, t = rep(0, nrow(obsloc))))

### 2.b Update the true process given the observations
## Find the Cmat by using the inla function
C2 <- inla.spde.make.A(mesh = MeshB, loc = obsloc)
L2 <- link(mglb_Q1, obs2, Cmat = C2)
e2 <- new("link_list",list(L2))
v2 <- new("block_list",list(G1 = mglb_Q1, O = obs2))
G2 <- new("Graph",e = e2,v = v2)
G_reduced <- compress(G2)
Results2 <- Infer(G_reduced)

mglb_x2_post <- Results2$Post_GMRF@rep
x2_mpost<- mglb_x2_post$x_mean
## Get the posterior mean and variance
x2_spost <- sqrt(mglb_x2_post$x_margvar)

## Compare mean square error with the true value
err2 <- x2_mpost - mglb_x2
mean(err2^2)

par(mfrow=c(2,3))
plot(mglb_x2)
plot(mglb_x2obs)
plot(x2_mpost, mglb_x2)
plot(err2)
plot(x2_spost)


### 2.c Plot and save results
## 2.c.1 Compare the true process and the observed values
## Palette setting 
clims <- range(c(mglb_x2all, mglb_y2, x2_mpost))
clens <- round((clims[2] - clims[1])*100) + 1
colpal <- terrain.colors(clens, alpha=0)
colx2obs <- colpal[round((mglb_x2obs - clims[1])*100) + 1]
colx2true <- colpal[round((mglb_x2 - clims[1])*100) + 1]
coly2 <- colpal[round((mglb_y2 - clims[1])*100) + 1]
colxp2 <- colpal[round((x2_mpost - clims[1])*100) + 1]
## Start plotting
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## Plot the true process
par3d(zoom = 0.8)
plot3d(obsloc,  col = colx2obs, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens, nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("The true process")
axis(1)})
## plot the observed value
next3d(reuse = FALSE)
par3d(zoom=0.8)
plot3d(obsloc,  col = coly2, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens), axes = FALSE,xlab = "",ylab = "")
title("Observed values")
axis(1)})
## Finish plotting and save the plot as an html
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/PvsObs2.html", width = 1500, reuse = TRUE)

## 2.c.2 Compare the Posterior Mean and variances
## reset palette
climss <- round(range(x2_spost*20000))
clenss <- climss[2] - climss[1] + 1
colpals <- heat.colors(clenss, alpha=0)
colsp2 <- colpals[round(x2_spost*20000) - climss[1]+1]
## Start plotting
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## The posterior mean
par3d(zoom = 0.8)
plot3d(obsloc,  col = colxp2, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx2true, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation

next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("Posterior mean")
axis(1)})


next3d(reuse = FALSE)
par3d(zoom=0.8)
## The posterior marginal std
plot3d(obsloc, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colsp2, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation

next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clenss,nrow=clenss)
y=1
x=seq(min(x2_spost),max(x2_spost),len=clenss)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=heat.colors(clenss),axes=FALSE,xlab="",ylab="")
title("Posterior standard error")
axis(1)})
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/posterior2.html", width = 1500, reuse = TRUE)

