##################################################################################
##         Test1     Point observations and S2 = S1                             ##
##################################################################################
##       Test script for simulate and estimate a univariate process             ##
##   We use the coarse mesh generated on the globe and simulate a univariate GP ##
## with zero mean and matern kernal as the true process. Then the observed data ##
## is assumed to be true process plus Gaussian error.                           ##
##   We then infer the true process from the observatiosn by using the MVST     ##
## framework and plot the posterior means and error bars.                       ##
##                                                                              ##
## ***Mesh***                                                                   ##
## * We use the mesh saved in the object MeshGlobe.RData                        ##
##   which was generated by the script Mesh/globe_INLA.R                        ##
##                                                                              ##
## ***Steps***                                                                  ##
## * 0. Initialising and load the previously generated Mesh grid                ##
## * For situation k, we do                                                     ##
## * a. Simulate the true process and observations                              ##
## * b. Infer the process from observations                                     ##
## * c. Plot the results and save                                               ##
##################################################################################
#### 0. Set working directory, load data and packages 
setwd("O:/glbm/TestMVST/R")
load("../Results/Mesh/MeshB.RData")
library(INLA)
library(rgdal)
library(maptools)
library(GEOmap)
library(rgl)

library(dplyr)
library(ggplot2)
library(MVST)

### Set seed for reproducible results
set.seed(11)

################################################################################
## Asssume the true process follows a GP with zero mean and Matern kernel.    ##
## The true process is simulated at the triangulation vertices.               ## 
##                                                                            ##
## Denote by S1 the set of triangle vertices and                              ##
## S2 a set of spatial units where the observations are taken.                ##
################################################################################
################################################################################
### 1.a Simulate the true process and observed data 
mglb_tv <- MeshB$loc # extract the triangulation vertices
mglb_S1 <- Matern(as.matrix(dist(mglb_tv)), nu = 3/2, var = 4, kappa = 0.1) # create the Matern covmat

## Use a GMRF to approximate the true GP
mglb_Q1 <- GMRF(Q = as(chol2inv(chol(mglb_S1)),"dgCMatrix")) # the precmat
mglb_x1 <- sample_GMRF(mglb_Q1) # simulate the true processs

## Simulate the observations, assume the error is Gaussian with sd = 0.1
sd1 <- 0.1
mglb_y1 <- mglb_x1 + rnorm(length(mglb_x1))*sd1
obs <- Obs(df=data.frame(x = mglb_tv[,1], y = mglb_tv[,2], w = mglb_tv[,3], z = mglb_y1, std = sd1, t = rep(0, nrow(mglb_tv))))

### 1.b Update the true process given the observations
## 1.b.1 Supply a user-defined Cmat
C1 <- Imat(nrow(mglb_tv))

## 1.b.2 use a GMRF basis and find the Cmat by FindC 
## Create the finite element object from the inla mesh
MeshB_fem <- inla.mesh.fem(MeshB, order = 2)
MeshBf <- initFEbasis(p=MeshB$loc,
                      t=MeshB$graph$tv,
                      M=MeshB_fem$c1,
                      K=MeshB_fem$g1)
mglb_p <- GMRF_basis(mglb_Q1, Basis = MeshBf)

## Build the LinkGo obj
L1 <- link(mglb_p, obs)  # build from process
L1c <- link(mglb_Q1, obs, Cmat = C1) #build by supplying Cmat

## Do inference
e <- new("link_list",list(L1))
v <- new("block_list",list(G1 = mglb_Q1, O = obs))
G <- new("Graph",e = e,v = v)
G_reduced <- compress(G)
Results1 <- Infer(G_reduced)

## extract posterior results
mglb_x1_post <- Results1$Post_GMRF@rep
x1_mpost<- mglb_x1_post$x_mean
## Get the posterior mean and variance
x1_spost <- sqrt(mglb_x1_post$x_margvar)

## Compare mean square error with the true value
resid1 <- x1_mpost - mglb_y1
err1 <- x1_mpost - mglb_x1
mean(resid1^2)
mean(err1^2)

par(mfrow=c(3,3))
plot(mglb_y1, mglb_x1)
plot(mglb_y1, x1_mpost)
plot(x1_mpost, mglb_x1)

plot(mglb_x1)
plot(mglb_y1)
plot(x1_mpost)


plot(err1)
plot(resid1)
plot(x1_spost)
### 1.c Plot and save results
## 1.c.1 Compare the true process and the observed values
## Palette setting 
clims <- range(c(mglb_x1, mglb_y1, x1_mpost))
clens <- round((clims[2] - clims[1])*100) + 1
colpal <- terrain.colors(clens, alpha=0)
colx1 <- colpal[round((mglb_x1 - clims[1])*100) + 1]
coly1 <- colpal[round((mglb_y1 - clims[1])*100) + 1]
colxp1 <- colpal[round((x1_mpost - clims[1])*100) + 1]
## Start plotting 
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## Plot the true process
par3d(zoom = 0.8)
plot3d(mglb_tv,  col = colx1, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colx1, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## The color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens, nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("The true process")
axis(1)})
## Plot the observed values
next3d(reuse = FALSE)
par3d(zoom=0.8)
plot3d(mglb_tv,  col = coly1, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = coly1, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## The color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col = terrain.colors(clens), axes = FALSE,xlab = "",ylab = "")
title("Observed values")
axis(1)})
## Finish plotting and save the plots as an html
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/PvsObs1.html", width = 1500, reuse = TRUE) 

## 1.c.2 Compare the Posterior Mean and variances
## reset palette
climss <- round(range(x1_spost*20000))
clenss <- climss[2] - climss[1] + 1
colpals <- heat.colors(clenss, alpha=0)
colsp <- colpals[round(x1_spost*20000) - climss[1]+1]
## Start plotting
open3d()
par3d(windowRect = c(100, 100, 1800, 900))
layout3d(matrix(1:4, 2,2), heights = c(8,2), sharedMouse = TRUE)
## Plot the posterior mean
par3d(zoom = 0.8)
plot3d(mglb_tv,  col = colxp1, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colxp1, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## Plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:clens,nrow = clens)
y=1
x=seq(clims[1],clims[2],len = clens)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=terrain.colors(clens),axes=FALSE,xlab="",ylab="")
title("Posterior mean")
axis(1)})
## Plot the marginal std
next3d(reuse = FALSE)
par3d(zoom=0.8)
plot3d(mglb_tv,  col = colsp, cex = 2, xlab = "", ylab = "", zlab = "", axe=FALSE) # plot the vertices
plot(MeshB, rgl = TRUE, col = colsp, edge.color = rgb(0, 0.5, 0.6, alpha =0.1), add = TRUE) # add the triangulation
## Plot the color bar
next3d(reuse = FALSE)
bgplot3d({z=matrix(1:148,nrow=148)
y=1
x=seq(min(x1_spost),max(x1_spost),len=148)
par(cex = 1.5, fin = c(8, 1), mai = c(0,0, 0.5, 0), oma = c(1, 0, 0, 0))
image(x,y,z,col=heat.colors(148),axes=FALSE,xlab="",ylab="")
title("Posterior standard error")
axis(1)})
## Finish plot and save it as an html
rgl.close()
#writeWebGL(dir = "../Results/GIAtest", filename= "../Results/GIAtest/posterior1.html", width = 1500, reuse = TRUE)

save(MeshB,mglb_Q1, file = "C:/Users/zs16444/Local Documents/GlobalMass/TestIO/sim_1.RData")
save.image(file = "C:/Users/zs16444/Local Documents/GlobalMass/TestIO/Sim1all.RData")
