##################################################################################
##         Test1     Point observations and S2 = S1                             ##
##################################################################################
##       Test script for simulate and estimate a univariate process             ##
##   We use the coarse mesh generated on the globe and simulate a univariate GP ##
## with zero mean and matern kernal as the true process. Then the observed data ##
## is assumed to be true process plus Gaussian error.                           ##
##   We then infer the true process from the observatiosn by using the MVST     ##
## framework and plot the posterior means and error bars.                       ##
##                                                                              ##
## ***Mesh***                                                                   ##
## * We use the mesh saved in the object MeshGlobe.RData                        ##
##   which was generated by the script Mesh/globe_INLA.R                        ##
##                                                                              ##
## ***Steps***                                                                  ##
## * 0. Initialising and load the previously generated Mesh grid                ##
## * For situation k, we do                                                     ##
## * a. Simulate the true process and observations                              ##
## * b. Infer the process from observations                                     ##
## * c. Plot the results and save                                               ##
##################################################################################
#### 0. Set working directory, load data and packages 
install.packages("INLA", repos="https://www.math.ntnu.no/inla/R/stable")
library(devtools)
install_github("andrewzm/MVST",build_vignettes=F,dependencies=T)

load("../Results/Mesh/MeshB.RData")
library(INLA)
library(rgdal)
library(maptools)
library(GEOmap)
library(rgl)

library(dplyr)
library(ggplot2)
library(MVST)

### Set seed for reproducible results
set.seed(11)

################################################################################
## Asssume the true process follows a GP with zero mean and Matern kernel.    ##
## The true process is simulated at the triangulation vertices.               ## 
##                                                                            ##
## Denote by S1 the set of triangle vertices and                              ##
## S2 a set of spatial units where the observations are taken.                ##
################################################################################
################################################################################
### 1.a Simulate the true process and observed data 
mglb_tv <- MeshB$loc # extract the triangulation vertices
mglb_S1 <- Matern(as.matrix(dist(mglb_tv)), nu = 3/2, var = 4, kappa = 0.1) # create the Matern covmat

## Use a GMRF to approximate the true GP
mglb_Q1 <- GMRF(Q = as(chol2inv(chol(mglb_S1)),"dgCMatrix")) # the precmat
mglb_x1 <- sample_GMRF(mglb_Q1) # simulate the true processs

## Simulate the observations, assume the error is Gaussian with sd = 0.1
sd1 <- 0.1
mglb_y1 <- mglb_x1 + rnorm(length(mglb_x1))*sd1
obs <- Obs(df=data.frame(x = mglb_tv[,1], y = mglb_tv[,2], w = mglb_tv[,3], z = mglb_y1, std = sd1, t = rep(0, nrow(mglb_tv))))

### 1.b Update the true process given the observations
## 1.b.1 Supply a user-defined Cmat
C1 <- Imat(nrow(mglb_tv))

## 1.b.2 use a GMRF basis and find the Cmat by FindC 
## Create the finite element object from the inla mesh
MeshB_fem <- inla.mesh.fem(MeshB, order = 2)
MeshBf <- initFEbasis(p=MeshB$loc,
                      t=MeshB$graph$tv,
                      M=MeshB_fem$c1,
                      K=MeshB_fem$g1)
mglb_p <- GMRF_basis(mglb_Q1, Basis = MeshBf)

## Build the LinkGo obj
L1 <- link(mglb_p, obs)  # build from process
L1c <- link(mglb_Q1, obs, Cmat = C1) #build by supplying Cmat

## Do inference
e <- new("link_list",list(L1))
v <- new("block_list",list(G1 = mglb_Q1, O = obs))
G <- new("Graph",e = e,v = v)
G_reduced <- compress(G)
Results1 <- Infer(G_reduced)

## extract posterior results
mglb_x1_post <- Results1$Post_GMRF@rep
x1_mpost<- mglb_x1_post$x_mean
## Get the posterior mean and variance
x1_spost <- sqrt(mglb_x1_post$x_margvar)

## Compare mean square error with the true value
resid1 <- x1_mpost - mglb_y1
err1 <- x1_mpost - mglb_x1
mean(resid1^2)
mean(err1^2)

pdf("../Results/testplots.pdf", width = 10, length = 10)
par(mfrow=c(3,3))
plot(mglb_y1, mglb_x1)
plot(mglb_y1, x1_mpost)
plot(x1_mpost, mglb_x1)

plot(mglb_x1)
plot(mglb_y1)
plot(x1_mpost)


plot(err1)
plot(resid1)
plot(x1_spost)

dev.off()
