#### Test availabe R packages
install.packages(rgdal)
require(rgdal)
require(maptools)
require(GEOmap)
require(rgl)

require(dplyr)
require(ggplot2)
require(devtools)
require(knitr)
require(igraph)
require(R.utils)
require(maps)
require(magic)
