---
output:
  html_document:
  fig_height: 6
  fig_width: 8
---
  
# Test the "update theorem".
  
  ***
We test the update theorem using simulated data with fixed parameters. The purpose is to investigate the relationship between the prior uncertainties, the measurement error and the posterior predicted uncertainties rather than inference on the parameters.

Assume we have unobserved process $Y \sim \mathcal{N}(0, \Sigma)$ and observation $Z = Y + E$ where $E$ is the measurement error and $E \perp Z, E \sim \mathcal{N}(0, T)$. Also assume that the measurement errors are independent to each other so that $T$ is a diagonal matrix. Then the updated variance is $$\Sigma^* := \mbox{Var}(Y | Z) = \Sigma - \Sigma(\Sigma + T)^{-1}\Sigma$$.

In the following settings we calculate $\Sigma^*$ and compare $\Sigma^*_{ii}$ with $T_{ii}, \Sigma_{ii}$ and $\mbox{Var}(Y_i|Z_i)$ for processes on $R^2$ and $S^2$

   1.  $T \sim \Sigma$
   2.  $T \ll \Sigma$
   3.  $T$ varying with locations, eg. lattidute.

The precision matrix (inverse covariance) is generated by using the INLA SPDE approach.

***

## 1 Experiment on $R^2$
First experiment on the region $[0,1] \times[0,1] \subset R^2$. The latent process is 
```{r warning=FALSE, message=FALSE, cache=TRUE}
## load packages.
library(INLA)
if(Sys.info()['sysname'] == "Linux"){INLA:::inla.dynload.workaround()}
library(ggplot2)
library(gridExtra)


```